library(geosphere)
library(haven)
library(htmltools)
library(tidyverse)
library(leaflet)
library(leaflet.extras)
library(maptools)
library(officer)
library(raster)
library(rgdal)
library(rgeos)
library(rmapshaper)
library(sf)
library(shiny)
library(shinyalert)
library(shinyjs)
library(sp)
library(spdep)
library(httpuv)

options(shiny.reactlog = TRUE)
options(haven.show_pillar_labels = FALSE)
jsResetCode <- "shinyjs.reset = function() {history.go(0)}" 

#pais@data <- pais@data %>% mutate(DC=DISTRITO,ZC_LOC=LOC_ZON)
